apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpscaling
  namespace: golang
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
