apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: golang
spec:
  selector:
    matchLabels:
      app: go-deployment
  template:
    metadata:
      labels:
        app: go-deployment
    spec:    
      containers:
      - name: go-container
        image: tharun13055/go_project:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
