apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: roleforpod
  namespace: golang
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["gets","watch","list","delete","update","create"]
