apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: golang
spec:
  selector:
    app: go-deployment
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    
    
  

 

