apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: golang
spec:
  selector:
    app: go-deployment
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000 
    nodePort: 320000

 

